CREATE TABLE IF NOT EXISTS company (
	id IDENTITY NOT NULL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	code VARCHAR(5) NOT NULL,
	founded DATE NOT NULL,
	country VARCHAR(100),
	city VARCHAR(100),
	address VARCHAR(200),
	owner VARCHAR(200)
);